USE [master]
GO
/***** Object:  Database [schoolManagement]    Script Date: 31-07-2024 22:31:30 *****/
CREATE DATABASE [schoolManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'schoolManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\schoolManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'schoolManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\schoolManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [schoolManagement] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [schoolManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [schoolManagement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [schoolManagement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [schoolManagement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [schoolManagement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [schoolManagement] SET ARITHABORT OFF 
GO
ALTER DATABASE [schoolManagement] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [schoolManagement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [schoolManagement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [schoolManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [schoolManagement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [schoolManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [schoolManagement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [schoolManagement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [schoolManagement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [schoolManagement] SET  ENABLE_BROKER 
GO
ALTER DATABASE [schoolManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [schoolManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [schoolManagement] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [schoolManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [schoolManagement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [schoolManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [schoolManagement] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [schoolManagement] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [schoolManagement] SET  MULTI_USER 
GO
ALTER DATABASE [schoolManagement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [schoolManagement] SET DB_CHAINING OFF 
GO
ALTER DATABASE [schoolManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [schoolManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [schoolManagement] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [schoolManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [schoolManagement] SET QUERY_STORE = ON
GO
ALTER DATABASE [schoolManagement] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [schoolManagement]
GO
/***** Object:  Table [dbo].[Students]    Script Date: 31-07-2024 22:31:30 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[PhoneNumber] [nvarchar](100) NULL,
	[Age] [int] NOT NULL,
	[Photo] [nvarchar](255) NULL,
	[Class] [nvarchar](50) NULL,
	[RollNumber] [int] NOT NULL,
	[Active] [bit] NULL,
	[CreatedOn] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/***** Object:  Table [dbo].[StudentSubjectReferences]    Script Date: 31-07-2024 22:31:30 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudentSubjectReferences](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StudentId] [int] NOT NULL,
	[SubjectId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/***** Object:  Table [dbo].[Subjects]    Script Date: 31-07-2024 22:31:30 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Subjects](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Class] [nvarchar](50) NOT NULL,
	[Language] [nvarchar](255) NULL,
	[Active] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/***** Object:  Table [dbo].[SubjectTeacherReferences]    Script Date: 31-07-2024 22:31:30 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SubjectTeacherReferences](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TeacherId] [int] NOT NULL,
	[SubjectId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/***** Object:  Table [dbo].[Teachers]    Script Date: 31-07-2024 22:31:30 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teachers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[PhoneNumber] [nvarchar](100) NULL,
	[Photo] [nvarchar](255) NULL,
	[Age] [int] NOT NULL,
	[Sex] [nvarchar](10) NOT NULL,
	[Active] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Subjects] ON 
GO
INSERT [dbo].[Subjects] ([Id], [Name], [Class], [Language], [Active]) VALUES (1, N'Data Science', N'12', N'Hindi, Punjabi, German', 0)
GO
INSERT [dbo].[Subjects] ([Id], [Name], [Class], [Language], [Active]) VALUES (2, N'History', N'12', N'English, Hindi', 0)
GO
INSERT [dbo].[Subjects] ([Id], [Name], [Class], [Language], [Active]) VALUES (3, N'DotNet', N'7', N'English', 0)
GO
INSERT [dbo].[Subjects] ([Id], [Name], [Class], [Language], [Active]) VALUES (4, N'C++', N'12', N'English', 0)
GO
INSERT [dbo].[Subjects] ([Id], [Name], [Class], [Language], [Active]) VALUES (5, N'DataArt', N'12', N'English', 0)
GO
SET IDENTITY_INSERT [dbo].[Subjects] OFF
GO
ALTER TABLE [dbo].[Students]  WITH CHECK ADD CHECK  (([Age]>=(1) AND [Age]<=(120)))
GO
ALTER TABLE [dbo].[Teachers]  WITH CHECK ADD CHECK  (([Age]>=(1) AND [Age]<=(120)))
GO
USE [master]
GO
ALTER DATABASE [schoolManagement] SET  READ_WRITE 
GO
